// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bcfoverparRcppClean
List bcfoverparRcppClean(NumericVector y_, NumericVector z_, NumericVector w_, NumericVector x_con_, NumericVector x_mod_, List x_con_info_list, List x_mod_info_list, arma::mat random_des, arma::mat random_var, arma::mat random_var_ix, double random_var_df, int burn, int nd, int thin, int ntree_mod, int ntree_con, double lambda, double nu, double con_sd, double mod_sd, double con_alpha, double con_beta, double mod_alpha, double mod_beta, CharacterVector treef_con_name_, CharacterVector treef_mod_name_, CharacterVector treef_var_name_, CharacterVector treef_var_ratio_name_, int status_interval, bool RJ, bool use_mscale, bool use_bscale, bool b_half_normal, double trt_init, bool verbose_sigma, bool no_output, NumericVector x_var_, List x_var_info_list, int ntree_var, double var_lambda, double var_nu, double var_alpha, double var_beta, bool use_hetero, bool use_ratio, bool use_paired_mean_update, bool use_global_mean_update, int joint_mean_every, bool collapsed_mu_scale, bool use_mean_split_change, bool use_variance_split_change, int joint_variance_every, int paired_variance_every);
RcppExport SEXP _bcf_bcfoverparRcppClean(SEXP y_SEXP, SEXP z_SEXP, SEXP w_SEXP, SEXP x_con_SEXP, SEXP x_mod_SEXP, SEXP x_con_info_listSEXP, SEXP x_mod_info_listSEXP, SEXP random_desSEXP, SEXP random_varSEXP, SEXP random_var_ixSEXP, SEXP random_var_dfSEXP, SEXP burnSEXP, SEXP ndSEXP, SEXP thinSEXP, SEXP ntree_modSEXP, SEXP ntree_conSEXP, SEXP lambdaSEXP, SEXP nuSEXP, SEXP con_sdSEXP, SEXP mod_sdSEXP, SEXP con_alphaSEXP, SEXP con_betaSEXP, SEXP mod_alphaSEXP, SEXP mod_betaSEXP, SEXP treef_con_name_SEXP, SEXP treef_mod_name_SEXP, SEXP treef_var_name_SEXP, SEXP treef_var_ratio_name_SEXP, SEXP status_intervalSEXP, SEXP RJSEXP, SEXP use_mscaleSEXP, SEXP use_bscaleSEXP, SEXP b_half_normalSEXP, SEXP trt_initSEXP, SEXP verbose_sigmaSEXP, SEXP no_outputSEXP, SEXP x_var_SEXP, SEXP x_var_info_listSEXP, SEXP ntree_varSEXP, SEXP var_lambdaSEXP, SEXP var_nuSEXP, SEXP var_alphaSEXP, SEXP var_betaSEXP, SEXP use_heteroSEXP, SEXP use_ratioSEXP, SEXP use_paired_mean_updateSEXP, SEXP use_global_mean_updateSEXP, SEXP joint_mean_everySEXP, SEXP collapsed_mu_scaleSEXP, SEXP use_mean_split_changeSEXP, SEXP use_variance_split_changeSEXP, SEXP joint_variance_everySEXP, SEXP paired_variance_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z_(z_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w_(w_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_con_(x_con_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_mod_(x_mod_SEXP);
    Rcpp::traits::input_parameter< List >::type x_con_info_list(x_con_info_listSEXP);
    Rcpp::traits::input_parameter< List >::type x_mod_info_list(x_mod_info_listSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type random_des(random_desSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type random_var(random_varSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type random_var_ix(random_var_ixSEXP);
    Rcpp::traits::input_parameter< double >::type random_var_df(random_var_dfSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type ntree_mod(ntree_modSEXP);
    Rcpp::traits::input_parameter< int >::type ntree_con(ntree_conSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type con_sd(con_sdSEXP);
    Rcpp::traits::input_parameter< double >::type mod_sd(mod_sdSEXP);
    Rcpp::traits::input_parameter< double >::type con_alpha(con_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type con_beta(con_betaSEXP);
    Rcpp::traits::input_parameter< double >::type mod_alpha(mod_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type mod_beta(mod_betaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treef_con_name_(treef_con_name_SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treef_mod_name_(treef_mod_name_SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treef_var_name_(treef_var_name_SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treef_var_ratio_name_(treef_var_ratio_name_SEXP);
    Rcpp::traits::input_parameter< int >::type status_interval(status_intervalSEXP);
    Rcpp::traits::input_parameter< bool >::type RJ(RJSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mscale(use_mscaleSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bscale(use_bscaleSEXP);
    Rcpp::traits::input_parameter< bool >::type b_half_normal(b_half_normalSEXP);
    Rcpp::traits::input_parameter< double >::type trt_init(trt_initSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose_sigma(verbose_sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type no_output(no_outputSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_var_(x_var_SEXP);
    Rcpp::traits::input_parameter< List >::type x_var_info_list(x_var_info_listSEXP);
    Rcpp::traits::input_parameter< int >::type ntree_var(ntree_varSEXP);
    Rcpp::traits::input_parameter< double >::type var_lambda(var_lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type var_nu(var_nuSEXP);
    Rcpp::traits::input_parameter< double >::type var_alpha(var_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type var_beta(var_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_hetero(use_heteroSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ratio(use_ratioSEXP);
    Rcpp::traits::input_parameter< bool >::type use_paired_mean_update(use_paired_mean_updateSEXP);
    Rcpp::traits::input_parameter< bool >::type use_global_mean_update(use_global_mean_updateSEXP);
    Rcpp::traits::input_parameter< int >::type joint_mean_every(joint_mean_everySEXP);
    Rcpp::traits::input_parameter< bool >::type collapsed_mu_scale(collapsed_mu_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mean_split_change(use_mean_split_changeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_variance_split_change(use_variance_split_changeSEXP);
    Rcpp::traits::input_parameter< int >::type joint_variance_every(joint_variance_everySEXP);
    Rcpp::traits::input_parameter< int >::type paired_variance_every(paired_variance_everySEXP);
    rcpp_result_gen = Rcpp::wrap(bcfoverparRcppClean(y_, z_, w_, x_con_, x_mod_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_con_name_, treef_mod_name_, treef_var_name_, treef_var_ratio_name_, status_interval, RJ, use_mscale, use_bscale, b_half_normal, trt_init, verbose_sigma, no_output, x_var_, x_var_info_list, ntree_var, var_lambda, var_nu, var_alpha, var_beta, use_hetero, use_ratio, use_paired_mean_update, use_global_mean_update, joint_mean_every, collapsed_mu_scale, use_mean_split_change, use_variance_split_change, joint_variance_every, paired_variance_every));
    return rcpp_result_gen;
END_RCPP
}
// bcfSbcPriorDraw
List bcfSbcPriorDraw(NumericMatrix x_control, NumericMatrix x_moderate, NumericMatrix x_variance, NumericVector z, List cutpoints_control, List cutpoints_moderate, List cutpoints_variance, std::string variance_model, int ntree_control, int ntree_moderate, int ntree_variance, double sd_control, double sd_moderate, double base_control, double power_control, double base_moderate, double power_moderate, double variance_base, double variance_power, double sigma_nu, double sigma_lambda, double variance_nu_tree, double variance_lambda_tree, int min_leaf, int max_attempts);
RcppExport SEXP _bcf_bcfSbcPriorDraw(SEXP x_controlSEXP, SEXP x_moderateSEXP, SEXP x_varianceSEXP, SEXP zSEXP, SEXP cutpoints_controlSEXP, SEXP cutpoints_moderateSEXP, SEXP cutpoints_varianceSEXP, SEXP variance_modelSEXP, SEXP ntree_controlSEXP, SEXP ntree_moderateSEXP, SEXP ntree_varianceSEXP, SEXP sd_controlSEXP, SEXP sd_moderateSEXP, SEXP base_controlSEXP, SEXP power_controlSEXP, SEXP base_moderateSEXP, SEXP power_moderateSEXP, SEXP variance_baseSEXP, SEXP variance_powerSEXP, SEXP sigma_nuSEXP, SEXP sigma_lambdaSEXP, SEXP variance_nu_treeSEXP, SEXP variance_lambda_treeSEXP, SEXP min_leafSEXP, SEXP max_attemptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_control(x_controlSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_moderate(x_moderateSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_variance(x_varianceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< List >::type cutpoints_control(cutpoints_controlSEXP);
    Rcpp::traits::input_parameter< List >::type cutpoints_moderate(cutpoints_moderateSEXP);
    Rcpp::traits::input_parameter< List >::type cutpoints_variance(cutpoints_varianceSEXP);
    Rcpp::traits::input_parameter< std::string >::type variance_model(variance_modelSEXP);
    Rcpp::traits::input_parameter< int >::type ntree_control(ntree_controlSEXP);
    Rcpp::traits::input_parameter< int >::type ntree_moderate(ntree_moderateSEXP);
    Rcpp::traits::input_parameter< int >::type ntree_variance(ntree_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type sd_control(sd_controlSEXP);
    Rcpp::traits::input_parameter< double >::type sd_moderate(sd_moderateSEXP);
    Rcpp::traits::input_parameter< double >::type base_control(base_controlSEXP);
    Rcpp::traits::input_parameter< double >::type power_control(power_controlSEXP);
    Rcpp::traits::input_parameter< double >::type base_moderate(base_moderateSEXP);
    Rcpp::traits::input_parameter< double >::type power_moderate(power_moderateSEXP);
    Rcpp::traits::input_parameter< double >::type variance_base(variance_baseSEXP);
    Rcpp::traits::input_parameter< double >::type variance_power(variance_powerSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_nu(sigma_nuSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_lambda(sigma_lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type variance_nu_tree(variance_nu_treeSEXP);
    Rcpp::traits::input_parameter< double >::type variance_lambda_tree(variance_lambda_treeSEXP);
    Rcpp::traits::input_parameter< int >::type min_leaf(min_leafSEXP);
    Rcpp::traits::input_parameter< int >::type max_attempts(max_attemptsSEXP);
    rcpp_result_gen = Rcpp::wrap(bcfSbcPriorDraw(x_control, x_moderate, x_variance, z, cutpoints_control, cutpoints_moderate, cutpoints_variance, variance_model, ntree_control, ntree_moderate, ntree_variance, sd_control, sd_moderate, base_control, power_control, base_moderate, power_moderate, variance_base, variance_power, sigma_nu, sigma_lambda, variance_nu_tree, variance_lambda_tree, min_leaf, max_attempts));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_TreeSamples();

static const R_CallMethodDef CallEntries[] = {
    {"_bcf_bcfoverparRcppClean", (DL_FUNC) &_bcf_bcfoverparRcppClean, 53},
    {"_bcf_bcfSbcPriorDraw", (DL_FUNC) &_bcf_bcfSbcPriorDraw, 25},
    {"_rcpp_module_boot_TreeSamples", (DL_FUNC) &_rcpp_module_boot_TreeSamples, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bcf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
